/*
 * This Java source file was generated by the Grade 'init' task.
 */
package meuprimeiroprojetooo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       Equipe EquipeFerrari = new Equipe();
       EquipeFerrari.p1 = new Piloto("Leclerc", 23);
       EquipeFerrari.p2 = new Piloto("Sainz", 25);
       EquipeFerrari.v1 = new Veiculo(new MotorDeFerrari());
       EquipeFerrari.v2 = new Veiculo(new MotorDeFerrari());
       EquipeFerrari.mecanicos.add(new Mecanico());
       EquipeFerrari.mecanicos.add(new Mecanico());
       EquipeFerrari.mecanicos.add(new Mecanico());
       EquipeFerrari.mecanicos.add(new Mecanico());
       EquipeFerrari.mecanicos.add(new Mecanico());
       EquipeFerrari.mecanicos.add(new Mecanico());
       
       Equipe EquipeMercedez = new Equipe();
       EquipeMercedez.p1 = new Piloto("Hamilton", 24);
       EquipeMercedez.p2 = new Piloto("Bottas", 26);
       EquipeMercedez.v1 = new Veiculo(new MotorDeMercedez());
       EquipeMercedez.v2 = new Veiculo(new MotorDeMercedez());
       EquipeMercedez.mecanicos.add(new Mecanico());
       EquipeMercedez.mecanicos.add(new Mecanico());
       EquipeMercedez.mecanicos.add(new Mecanico());
       EquipeMercedez.mecanicos.add(new Mecanico());
       EquipeMercedez.mecanicos.add(new Mecanico());
       EquipeMercedez.mecanicos.add(new Mecanico());
       
       Equipe EquipeForceIndy = new Equipe();
       EquipeForceIndy.p1 = new Piloto("Hulkenberg", 27);
       EquipeForceIndy.p2 = new Piloto("Perez", 25);
       EquipeForceIndy.v1 = new Veiculo(new MotorForceIndy());
       EquipeForceIndy.v2 = new Veiculo(new MotorForceIndy());
       EquipeForceIndy.mecanicos.add(new Mecanico());
       EquipeForceIndy.mecanicos.add(new Mecanico());
       EquipeForceIndy.mecanicos.add(new Mecanico());
       EquipeForceIndy.mecanicos.add(new Mecanico());
       EquipeForceIndy.mecanicos.add(new Mecanico());
       EquipeForceIndy.mecanicos.add(new Mecanico());
       
       System.out.println(EquipeFerrari.p1.nome);
    }
}
